#!/bin/bash

# echo "$( dirname "${BASH_SOURCE[0]}" )"

if [ $# -eq 1  ]
then
    PROJECT_NAME="AdventCalendar2019-$1"
    dotnet new sln -o $PROJECT_NAME
    cd $PROJECT_NAME
    dotnet new classLib -lang F# -o Core
    dotnet new console -lang F# -o Console
    dotnet new xunit -lang F# -o Tests
    dotnet add  Tests/Tests.fsproj package FsUnit

    dotnet add Tests/Tests.fsproj reference Core/Core.fsproj
    dotnet add Console/Console.fsproj reference Core/Core.fsproj

    dotnet sln add Core/Core.fsproj
    dotnet sln add Tests/Tests.fsproj
    dotnet sln add Console/Console.fsproj

    DIR_PATH=".$( dirname "${BASH_SOURCE[0]}" )/"
    BUILD_FILE_PATH="${DIR_PATH}build.yml"
    GITHUB_FOLDER_PATH=".github/workflows"
    echo "${DIR_PATH} - ${BUILD_FILE_PATH} - ${GITHUB_FOLDER_PATH}"
    mkdir -p $GITHUB_FOLDER_PATH
    cp $BUILD_FILE_PATH $GITHUB_FOLDER_PATH

    git init
    curl https://gist.githubusercontent.com/geoder101/aa2ab1ab417fbc52bb8b/raw/1a1642c53f0736f55e9a9797e802788c24c99b73/.gitignore >> .gitignore
    git add -A
    git commit -m "initial commit <3"
else
    echo "You should give the day of the event :)"
fi